"""kredi: paket ve ledger

Revision ID: 2d6ec5c0049e
Revises: ad4284412a95
Create Date: 2026-08-25 06:52:03.371822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6ec5c0049e'
down_revision: Union[str, Sequence[str], None] = 'ad4284412a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=80), nullable=False),
    sa.Column('ders_adedi', sa.Integer(), nullable=False),
    sa.Column('gecerlilik_gun', sa.Integer(), nullable=False),
    sa.Column('fiyat_kurus', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ders_adedi > 0', name='ck_package_ders_adedi'),
    sa.CheckConstraint('gecerlilik_gun > 0', name='ck_package_gecerlilik'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('baslangic', sa.Date(), nullable=False),
    sa.Column('bitis', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_packages_member_id'), 'member_packages', ['member_id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('member_package_id', sa.Integer(), nullable=True),
    sa.Column('tip', sa.String(length=24), nullable=False),
    sa.Column('miktar', sa.Integer(), nullable=False),
    sa.Column('sebep', sa.String(length=200), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['member_package_id'], ['member_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_booking_id'), 'credit_ledger', ['booking_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_member_id'), 'credit_ledger', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_ledger_member_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_booking_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_member_packages_member_id'), table_name='member_packages')
    op.drop_table('member_packages')
    op.drop_table('packages')
    # ### end Alembic commands ###
