"""add_notifications_and_device_tokens

Revision ID: 9605633b3f10
Revises: e2f1d390ecf8
Create Date: 2026-09-01 16:04:56.407212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9605633b3f10'
down_revision: Union[str, Sequence[str], None] = 'e2f1d390ecf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('device_token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_tokens_device_token'), 'device_tokens', ['device_token'], unique=True)
    op.create_index(op.f('ix_device_tokens_member_id'), 'device_tokens', ['member_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=120), nullable=False),
    sa.Column('mesaj', sa.Text(), nullable=False),
    sa.Column('tip', sa.String(length=40), nullable=False),
    sa.Column('okundu', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_member_id'), 'notifications', ['member_id'], unique=False)
    op.create_index(op.f('ix_notifications_okundu'), 'notifications', ['okundu'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_okundu'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_member_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_device_tokens_member_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_device_token'), table_name='device_tokens')
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
