"""program: ders tipi, salon, sablon, oturum

Revision ID: ad4284412a95
Revises: d57e567cad14
Create Date: 2026-08-25 06:33:55.361829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4284412a95'
down_revision: Union[str, Sequence[str], None] = 'd57e567cad14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=80), nullable=False),
    sa.Column('kontenjan', sa.Integer(), nullable=False),
    sa.Column('sure_dk', sa.Integer(), nullable=False),
    sa.Column('renk', sa.String(length=9), nullable=False),
    sa.Column('iptal_penceresi_saat', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('kontenjan > 0', name='ck_class_type_kontenjan'),
    sa.CheckConstraint('sure_dk > 0', name='ck_class_type_sure'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=80), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad')
    )
    op.create_table('schedule_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hafta_gunu', sa.Integer(), nullable=False),
    sa.Column('saat_dk', sa.Integer(), nullable=False),
    sa.Column('class_type_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('gecerli_baslangic', sa.Date(), nullable=False),
    sa.Column('gecerli_bitis', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hafta_gunu BETWEEN 0 AND 6', name='ck_template_gun'),
    sa.CheckConstraint('saat_dk BETWEEN 0 AND 1439', name='ck_template_saat'),
    sa.ForeignKeyConstraint(['class_type_id'], ['class_types.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslangic', sa.DateTime(timezone=True), nullable=False),
    sa.Column('class_type_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('kontenjan', sa.Integer(), nullable=False),
    sa.Column('dolu_sayi', sa.Integer(), nullable=False),
    sa.Column('durum', sa.String(length=16), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dolu_sayi >= 0 AND dolu_sayi <= kontenjan', name='ck_session_dolu_sayi'),
    sa.ForeignKeyConstraint(['class_type_id'], ['class_types.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['schedule_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'baslangic', name='uq_salon_saat')
    )
    op.create_index(op.f('ix_class_sessions_baslangic'), 'class_sessions', ['baslangic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_sessions_baslangic'), table_name='class_sessions')
    op.drop_table('class_sessions')
    op.drop_table('schedule_templates')
    op.drop_table('rooms')
    op.drop_table('class_types')
    # ### end Alembic commands ###
