"""rezervasyon: bookings ve waitlist_entries

Revision ID: cef9c48efd75
Revises: 2d6ec5c0049e
Create Date: 2026-08-25 07:05:48.052693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef9c48efd75'
down_revision: Union[str, Sequence[str], None] = '2d6ec5c0049e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('durum', sa.String(length=16), nullable=False),
    sa.Column('kaynak', sa.String(length=8), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_member_id'), 'bookings', ['member_id'], unique=False)
    op.create_index(op.f('ix_bookings_session_id'), 'bookings', ['session_id'], unique=False)
    op.create_index('uq_aktif_rezervasyon', 'bookings', ['member_id', 'session_id'], unique=True, postgresql_where=sa.text("durum = 'booked'"))
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sira', sa.Integer(), nullable=False),
    sa.Column('teklif_bitis', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kullanildi', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_entries_member_id'), 'waitlist_entries', ['member_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_session_id'), 'waitlist_entries', ['session_id'], unique=False)
    op.create_index('uq_bekleme', 'waitlist_entries', ['member_id', 'session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_bekleme', table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_session_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_member_id'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index('uq_aktif_rezervasyon', table_name='bookings', postgresql_where=sa.text("durum = 'booked'"))
    op.drop_index(op.f('ix_bookings_session_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_member_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
