"""add_notification_campaigns

Revision ID: d2dcd6f3048b
Revises: 9605633b3f10
Create Date: 2026-09-01 16:09:43.077838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2dcd6f3048b'
down_revision: Union[str, Sequence[str], None] = '9605633b3f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=120), nullable=False),
    sa.Column('mesaj', sa.Text(), nullable=False),
    sa.Column('hedef_kitle', sa.String(length=40), nullable=False),
    sa.Column('zamanlama_tipi', sa.String(length=40), nullable=False),
    sa.Column('zamanlama_saat', sa.String(length=10), nullable=True),
    sa.Column('son_gonderim_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gonderilen_sayisi', sa.Integer(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_campaigns')
    # ### end Alembic commands ###
