name: Shorebird iOS Patch

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'android/lib/**'
      - 'android/pubspec.yaml'
      - 'android/pubspec.lock'

jobs:
  patch_ios:
    name: iOS Patch (Shorebird)
    runs-on: macos-latest

    steps:
      - name: 📥 Kodu İndir
        uses: actions/checkout@v4

      - name: 🐦 Flutter Kur
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'
          cache: true

      - name: 📦 Bağımlılıkları Yükle
        run: flutter pub get
        working-directory: android

      - name: 🐦 Shorebird Kur
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      - name: 🚀 iOS Patch Gönder
        run: printf 'y\ny\ny\n' | shorebird patch ios --no-codesign --allow-asset-diffs --allow-podfile-lock-diffs
        working-directory: android
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
